// packages/desktop-tauri/src/lib/components/xcloud/TitleRow.svelte
<script lang="ts">
	import GameTitle from '$lib/components/game/GameTitle.svelte';
	import Loader from '$lib/components/ui/Loader.svelte';

	let {
		title,
		titleIds
	}: {
		title: import('svelte').Snippet;
		titleIds: string[];
	} = $props();
</script>

<section class="mb-8">
	<h2 class="text-lg font-semibold text-white mb-4">
		{@render title()}
	</h2>
	<div class="flex gap-4 overflow-x-auto pb-2">
		{#if titleIds.length === 0}
			<Loader />
		{:else}
			{#each titleIds as id (id)}
				<GameTitle titleId={id} />
			{/each}
		{/if}
	</div>
</section>

// packages/desktop-v3/renderer/components/xcloud/TitleRow.tsx
import GameTitle from '../game/GameTitle'
import Loader from '../ui/Loader'

export default function TitleRow({
  title,
  titleIds,
}: {
  title: React.ReactNode
  titleIds: string[]
}) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold text-white mb-4">{title}</h2>
      <div className="flex gap-4 overflow-x-auto pb-2">
        {titleIds.length === 0 ? (
          <Loader />
        ) : (
          titleIds.map((id) => <GameTitle key={id} titleId={id} />)
        )}
      </div>
    </section>
  )
}
