// packages/desktop/renderer/pages/settings/webui.tsx
import React from 'react'
import Head from 'next/head'
import SettingsSidebar from '../../components/settings/sidebar'
import Card from '../../components/ui/card'
import Button from '../../components/ui/button'
import Ipc from '../../lib/ipc'
import { useSettings } from '../../context/userContext'
import { useTranslation } from 'react-i18next'


function SettingsWebUI() {
    const { settings, setSettings} = useSettings()
    const [webuiRunning, setWebuiRunning] = React.useState(false)
    const { t } = useTranslation()

    React.useEffect(() => {
        const webuiStatusInterval = setInterval(() => {
            Ipc.send('settings', 'getWebUIStatus').then((status) => {
                setWebuiRunning(status)
            })
        }, 1000)

        Ipc.send('settings', 'getWebUIStatus').then((status) => {
            setWebuiRunning(status)
        })

        return () => {
            clearInterval(webuiStatusInterval)
        }
    })

    function setWebUIEnabled(){
        Ipc.send('settings', (webuiRunning) ? 'stopWebUI' : 'startWebUI').then((status) => {
            setWebuiRunning(status)
        })
    }

    function setWebUIAutostart(){
        setSettings({
            ...settings,
            webui_autostart: (! settings.webui_autostart),
        })
    }

    function setWebUIPort(e){
        setSettings({
            ...settings,
            webui_port: e.target.value,
        })
    }

    return (
        <React.Fragment>
            <Head>
                <title>Blacklight - {t('settings.webUI.pageTitle')}</title>
            </Head>

            <SettingsSidebar>
                <Card>
                    <h1>{t('settings.webUI.title')}</h1>

                    <p>
                        <label>{t('settings.webUI.enableWebUILabel')}</label>
                        <label style={{ minWidth: 0 }}>
                            <Button onClick={ () => setWebUIEnabled() } disabled={ window.Blacklight.isWebUI() } className={ ((webuiRunning) ? 'btn-cancel' : 'btn-primary') + ' btn-small' } label={ webuiRunning ? t('settings.webUI.stopWebUIBtn') : t('settings.webUI.startWebUIBtn') }></Button> &nbsp;
                            <Button onClick={ () => window.Blacklight.openExternal('http://127.0.0.1:'+settings.webui_port) } className={ 'btn-small' } label={ t('settings.webUI.openWebUIBtn') }></Button>
                        </label>
                    </p>

                    <p>
                        <label>{t('settings.webUI.autostartLabel')}</label>
                        <label style={{ minWidth: 0 }}>
                            <input type='checkbox' onChange={ setWebUIAutostart } checked={settings.webui_autostart} />&nbsp; ({ settings.webui_autostart ? t('settings.webUI.autostartEnabled') : t('settings.webUI.autostartDisabled') })
                        </label>
                    </p>

                    <p>
                        <label>{t('settings.webUI.portLabel')}</label>
                        <label style={{ minWidth: 0 }}>
                            <input type="text" onChange={ setWebUIPort} className="text" placeholder={t('settings.webUI.portPlaceholder')} value={ settings.webui_port || 9003 } />
                        </label>
                    </p>
                </Card>
            </SettingsSidebar>


        </React.Fragment>
    )
}

export default SettingsWebUI

// packages/desktop-tauri/src/routes/settings/webui/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { t } from '$lib/i18n';
	import { getSettings, setSettings } from '$lib/stores/settings.svelte';
	import {
		getWebuiApi,
		isDesktopShell,
		isWebUIMode,
		openExternal
	} from '$lib/runtime';
	import AppLayout from '$lib/components/layout/AppLayout.svelte';
	import SettingsSidebar from '$lib/components/settings/SettingsSidebar.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import Button from '$lib/components/ui/Button.svelte';

	const settings = $derived(getSettings());
	const inWebUI = $derived(isWebUIMode());
	const webuiApi = getWebuiApi();

	let running = $state(false);

	onMount(() => {
		if (!webuiApi) return;
		const refresh = () => webuiApi.getStatus().then((r) => (running = r));
		refresh();
		const interval = setInterval(refresh, 1000);
		return () => clearInterval(interval);
	});

	function syncToMain(next: ReturnType<typeof getSettings>) {
		webuiApi?.saveSettings({
			webui_autostart: next.webui_autostart,
			webui_port: Number(next.webui_port) || 9003
		});
	}

	async function toggleServer() {
		if (!webuiApi) return;
		if (running) {
			await webuiApi.stop();
		} else {
			await webuiApi.start(Number(settings.webui_port) || 9003);
		}
		running = await webuiApi.getStatus();
	}

	function openInBrowser() {
		const port = Number(settings.webui_port) || 9003;
		void openExternal(`http://127.0.0.1:${port}/home`);
	}
</script>

<AppLayout title={t('settings.webUI.pageTitle')}>
	<div class="flex gap-8">
		<SettingsSidebar />
		<div class="flex-1">
			<Card>
				<h1 class="text-xl font-bold text-white mb-4">{t('settings.webUI.title')}</h1>
				<div class="space-y-4 text-white/80">
					<div class="flex items-center justify-between gap-4">
						<span>{t('settings.webUI.enableWebUILabel')}</span>
						<div class="flex gap-2">
							<Button
								label={running
									? t('settings.webUI.stopWebUIBtn')
									: t('settings.webUI.startWebUIBtn')}
								onclick={toggleServer}
								disabled={inWebUI}
								class={running ? 'bg-red-800 hover:bg-red-700' : ''}
							/>
							<Button label={t('settings.webUI.openWebUIBtn')} onclick={openInBrowser} />
						</div>
					</div>

					{#if inWebUI}
						<p class="text-orange-300 text-sm">
							You are viewing Blacklight through WebUI. Server controls are disabled in this mode.
						</p>
					{/if}

					{#if isDesktopShell() && !isWebUIMode()}
						<p class="text-white/50 text-sm">
							Tauri shell uses the local API server on 127.0.0.1. Start it before opening streams if
							autostart is disabled.
						</p>
					{/if}

					<label class="flex items-center gap-3 cursor-pointer">
						<input
							type="checkbox"
							checked={settings.webui_autostart}
							disabled={inWebUI}
							onchange={(e) => {
								const next = {
									...settings,
									webui_autostart: (e.currentTarget as HTMLInputElement).checked
								};
								setSettings(next);
								syncToMain(next);
							}}
							class="accent-[#107C10]"
						/>
						<span>
							{t('settings.webUI.autostartLabel')} ({settings.webui_autostart
								? t('settings.webUI.autostartEnabled')
								: t('settings.webUI.autostartDisabled')})
						</span>
					</label>

					<div>
						<label class="block text-sm text-white/60 mb-1">{t('settings.webUI.portLabel')}</label>
						<input
							type="number"
							min="1024"
							max="65535"
							disabled={inWebUI}
							class="w-32 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white"
							placeholder={t('settings.webUI.portPlaceholder')}
							value={settings.webui_port}
							onchange={(e) => {
								const next = {
									...settings,
									webui_port: parseInt((e.currentTarget as HTMLInputElement).value) || 9003
								};
								setSettings(next);
								syncToMain(next);
							}}
						/>
					</div>

					<p class="text-white/40 text-sm">
						WebUI is available only on this machine at 127.0.0.1 (localhost). Authentication and
						streaming use HTTP tRPC in the browser.
					</p>
				</div>
			</Card>
		</div>
	</div>
</AppLayout>
