// packages/desktop-tauri/src/routes/xcloud/library/+page.svelte
<script lang="ts">
	import { t } from '$lib/i18n';
	import AppLayout from '$lib/components/layout/AppLayout.svelte';
	import Breadcrumb from '$lib/components/ui/Breadcrumb.svelte';
	import GameTitle from '$lib/components/game/GameTitle.svelte';
	import Loader from '$lib/components/ui/Loader.svelte';
	import {
		filterTitles,
		getCatalogIsLoading,
		getTitles
	} from '$lib/stores/titleCatalog.svelte';

	let filter = $state('');
	const titleIds = $derived(filter ? filterTitles(filter) : getTitles().map((t) => t.titleId));
</script>

<AppLayout title={t('page.xCloudLibrary.pageTitle')}>
	<Breadcrumb
		items={[
			{ href: '/home', label: t('page.xCloudLibrary.breadcrumb1') },
			{ href: '/xcloud/library', label: t('page.xCloudLibrary.breadcrumb2') }
		]}
	/>
	<div class="flex items-center gap-4 mb-6">
		<h1 class="text-2xl font-bold text-white">{t('page.xCloudLibrary.title')}</h1>
		<input
			type="text"
			placeholder={t('page.xCloudLibrary.searchPlaceholder')}
			class="flex-1 max-w-xs px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm"
			bind:value={filter}
		/>
	</div>
	{#if getCatalogIsLoading()}
		<Loader />
	{:else}
		<div class="flex flex-wrap gap-4">
			{#each titleIds as id (id)}
				<GameTitle titleId={id} />
			{/each}
		</div>
	{/if}
</AppLayout>

// packages/desktop/renderer/pages/xcloud/library.tsx
import React from 'react'
import Head from 'next/head'
import Ipc from '../../lib/ipc'
import Link from 'next/link'
import Loader from '../../components/ui/loader'
import ViewportGrid from '../../components/ui/viewportgrid'
import GameTitleDynamic from '../../components/ui/game/titledynamic'
import BreadcrumbBar from '../../components/ui/breadcrumbbar'
import { useQuery, QueryClient } from 'react-query'
import { useTranslation } from 'react-i18next'


function xCloudLibrary() {
    const { t } = useTranslation()
    const [filter, setFilter] = React.useState({
        name: '',
    })

    const xCloudTitles = useQuery('xCloudTitles', () => Ipc.send('xCloud', 'getTitles'), { staleTime: 300*1000 })
    const xCloudSearch = useQuery(['xCloudSearch', filter], () => Ipc.send('xCloud', 'filterTitles', filter))
    const queryClient = new QueryClient()

    function performFilter(){
        console.log(filter)

        // if(filter.name !== ''){
        //   // const xCloudSearch = useQuery('xCloudSearch', () => Ipc.send('xCloud', 'filterTitles', filter))
        queryClient.invalidateQueries('xCloudSearch')
        return (xCloudSearch.isFetched === true) ? xCloudSearch.data : xCloudTitles.data
        // }

        // return (xCloudSearch.isFetched === true) ? xCloudSearch.data : xCloudTitles.data
        return xCloudTitles.data
    }

    return (
        <React.Fragment>
            <Head>
                <title>Blacklight - {t('page.xCloudLibrary.pageTitle')}</title>
            </Head>

            <BreadcrumbBar>
                <Link href="/xcloud/home">{t('page.xCloudLibrary.breadcrumb1')}</Link>
                <Link href="/xcloud/library">{t('page.xCloudLibrary.breadcrumb2')}</Link>
            </BreadcrumbBar>

            <h2 className="title">
                {t('page.xCloudLibrary.title')}

                <input type="text" className="text h2-search" placeholder={t('page.xCloudLibrary.searchPlaceholder')} onChange={
                    (e) => {
                        setFilter({
                            name: e.target.value,
                        })
                    }
                }></input>
            </h2>

            <ViewportGrid key='library' drawPagination={true}>{
                (xCloudTitles.isFetched !== true) ? (<Loader></Loader>) : performFilter().map((item) => {
                    return (
                        <GameTitleDynamic
                            titleId={ item }
                            key={ item }
                        ></GameTitleDynamic>
                    )
                })
            }</ViewportGrid>

        </React.Fragment>
    )
}

export default xCloudLibrary
