// packages/desktop-v3/renderer/components/game/GameTitle.tsx
import Link from 'next/link'
import { useQuery } from '@tanstack/react-query'
import { useTRPC } from '../../utils/trpc'
import { useAuth } from '../../contexts/AuthContext'
import { useTitleCatalog } from '../../contexts/TitleCatalogContext'
import Loader from '../ui/Loader'
import { getProducts } from '../../lib/titles'

export default function GameTitle({ titleId }: { titleId: string }) {
  const trpc = useTRPC()
  const { getxHomeToken } = useAuth()
  const { getTitle } = useTitleCatalog()
  const cached = getTitle(titleId)

  const resolved = useQuery({
    ...trpc.gamepass_resolve_productid.queryOptions({
      token: getxHomeToken(),
      productId: cached?.productId || titleId,
    }),
    enabled: !cached?.catalogDetails,
    staleTime: 10 * 60 * 1000,
  })

  const products = getProducts(resolved.data)
  const product =
    cached?.catalogDetails ||
    (products ? (Object.values(products)[0] as Record<string, any>) : undefined)
  const name = product?.ProductTitle || titleId
  const image = product?.Image_Tile?.URL

  if (!product && (resolved.isLoading || !cached)) return <Loader />

  return (
    <div className="group relative w-[140px] shrink-0">
      <Link
        href={`/xcloud/info/${titleId}/`}
        className="absolute top-1 right-1 z-10 w-6 h-6 rounded bg-black/60 text-white/70 text-xs flex items-center justify-center opacity-0 group-hover:opacity-100"
        title="Info"
      >
        i
      </Link>
      <Link href={`/stream/xcloud_${titleId}/`} className="block">
        {image ? (
          <img
            src={`https:${image}`}
            alt={name}
            className="w-[140px] h-[140px] rounded object-cover"
          />
        ) : (
          <div className="w-[140px] h-[140px] rounded bg-white/5 flex items-center justify-center text-white/30 text-xs">
            {titleId}
          </div>
        )}
        <p className="mt-2 text-xs text-white/70 line-clamp-2">{name}</p>
      </Link>
    </div>
  )
}

// packages/desktop-tauri/src/lib/components/game/GameTitle.svelte
<script lang="ts">
	import { trpc } from '$lib/trpc';
	import { getxHomeToken } from '$lib/stores/auth.svelte';
	import { getTitle } from '$lib/stores/titleCatalog.svelte';
	import { getProducts } from '$lib/titles';
	import Loader from '$lib/components/ui/Loader.svelte';

	let { titleId }: { titleId: string } = $props();

	let product = $state<Record<string, unknown> | undefined>(undefined);
	let loading = $state(false);

	const cached = $derived(getTitle(titleId));

	$effect(() => {
		if (cached?.catalogDetails) {
			product = cached.catalogDetails;
			return;
		}

		let cancelled = false;
		loading = true;

		trpc.gamepass_resolve_productid
			.query({
				token: getxHomeToken(),
				productId: cached?.productId || titleId
			})
			.then((resolved) => {
				if (cancelled) return;
				const products = getProducts(resolved);
				product = products ? (Object.values(products)[0] as Record<string, unknown>) : undefined;
			})
			.finally(() => {
				if (!cancelled) loading = false;
			});

		return () => {
			cancelled = true;
		};
	});

	const name = $derived((product?.ProductTitle as string) || titleId);
	const image = $derived(product?.Image_Tile as { URL?: string } | undefined);
</script>

{#if !product && (loading || !cached)}
	<Loader />
{:else}
	<div class="group relative w-[140px] shrink-0">
		<a
			href="/xcloud/info/{titleId}"
			class="absolute top-1 right-1 z-10 w-6 h-6 rounded bg-black/60 text-white/70 text-xs flex items-center justify-center opacity-0 group-hover:opacity-100"
			title="Info"
		>
			i
		</a>
		<a href="/stream/xcloud_{titleId}" class="block">
			{#if image?.URL}
				<img
					src="https:{image.URL}"
					alt={name}
					class="w-[140px] h-[140px] rounded object-cover"
				/>
			{:else}
				<div
					class="w-[140px] h-[140px] rounded bg-white/5 flex items-center justify-center text-white/30 text-xs"
				>
					{titleId}
				</div>
			{/if}
			<p class="mt-2 text-xs text-white/70 line-clamp-2">{name}</p>
		</a>
	</div>
{/if}
