// packages/desktop-v3/renderer/pages/settings/input.tsx
import AppLayout from '../../components/layout/AppLayout'
import SettingsSidebar from '../../components/settings/SettingsSidebar'
import Card from '../../components/ui/Card'
import { useSettings } from '../../contexts/SettingsContext'

export default function SettingsInputPage() {
  const { settings, setSettings } = useSettings()

  const toggle = (
    key: 'controller_vibration' | 'input_mousekeyboard' | 'input_touch' | 'input_newgamepad',
  ) => {
    setSettings({ ...settings, [key]: !settings[key] })
  }

  return (
    <AppLayout title="Input Settings">
      <div className="flex gap-8">
        <SettingsSidebar />
        <div className="flex-1 space-y-4">
          {(
            [
              ['controller_vibration', 'Controller vibration'],
              ['input_mousekeyboard', 'Mouse & keyboard'],
              ['input_touch', 'Touch controls'],
              ['input_newgamepad', 'New gamepad driver'],
            ] as const
          ).map(([key, label]) => (
            <Card key={key}>
              <label className="flex items-center gap-3 text-white/80 cursor-pointer">
                <input
                  type="checkbox"
                  checked={settings[key] as boolean}
                  onChange={() => toggle(key as 'controller_vibration' | 'input_mousekeyboard' | 'input_touch' | 'input_newgamepad')}
                  className="accent-[#107C10]"
                />
                {label}
              </label>
            </Card>
          ))}
        </div>
      </div>
    </AppLayout>
  )
}

// packages/desktop-tauri/src/routes/settings/input/+page.svelte
<script lang="ts">
	import { getSettings, setSettings } from '$lib/stores/settings.svelte';
	import AppLayout from '$lib/components/layout/AppLayout.svelte';
	import SettingsSidebar from '$lib/components/settings/SettingsSidebar.svelte';
	import Card from '$lib/components/ui/Card.svelte';

	const settings = $derived(getSettings());

	const toggles = [
		['controller_vibration', 'Controller vibration'],
		['input_mousekeyboard', 'Mouse & keyboard'],
		['input_touch', 'Touch controls'],
		['input_newgamepad', 'New gamepad driver']
	] as const;

	function toggle(key: (typeof toggles)[number][0]) {
		setSettings({ ...settings, [key]: !settings[key] });
	}
</script>

<AppLayout title="Input Settings">
	<div class="flex gap-8">
		<SettingsSidebar />
		<div class="flex-1 space-y-4">
			{#each toggles as [key, label] (key)}
				<Card>
					<label class="flex items-center gap-3 text-white/80 cursor-pointer">
						<input
							type="checkbox"
							checked={settings[key]}
							onchange={() => toggle(key)}
							class="accent-[#107C10]"
						/>
						{label}
					</label>
				</Card>
			{/each}
		</div>
	</div>
</AppLayout>
