// packages/desktop-tauri/src/lib/components/layout/AppLayout.svelte
<script lang="ts">
	import Sidebar from '$lib/components/sidebar/Sidebar.svelte';
	import FriendsList from '$lib/components/sidebar/FriendsList.svelte';

	let { title, children }: { title?: string; children: import('svelte').Snippet } = $props();
</script>

<svelte:head>
	<title>{title ? `Blacklight - ${title}` : 'Blacklight'}</title>
</svelte:head>

<div class="flex h-screen bg-[#0d0d0d] bg-pattern overflow-hidden">
	<Sidebar />
	<main class="flex-1 overflow-hidden relative flex">
		<div class="flex-1 overflow-y-auto">
			<div
				class="absolute top-0 right-0 w-96 h-96 bg-[#107C10]/3 rounded-full blur-3xl pointer-events-none"
			></div>
			<div class="p-6 md:p-8 max-w-6xl mx-auto">
				{@render children()}
			</div>
		</div>
		<FriendsList />
	</main>
</div>

// packages/desktop-v3/renderer/components/layout/AppLayout.tsx
import Head from 'next/head'
import Sidebar from '../sidebar'
import FriendsList from '../sidebar/FriendsList'

export default function AppLayout({
  title,
  children,
}: {
  title?: string
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <title>{title ? `Blacklight - ${title}` : 'Blacklight'}</title>
      </Head>
      <div className="flex h-screen bg-[#0d0d0d] bg-pattern overflow-hidden">
        <Sidebar />
        <main className="flex-1 overflow-hidden relative flex">
          <div className="flex-1 overflow-y-auto">
            <div className="absolute top-0 right-0 w-96 h-96 bg-[#107C10]/3 rounded-full blur-3xl pointer-events-none" />
            <div className="p-6 md:p-8 max-w-6xl mx-auto">{children}</div>
          </div>
          <FriendsList />
        </main>
      </div>
    </>
  )
}
